# Generated by Django 5.2.7 on 2025-10-30 21:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Yönetici'), ('agent', 'Acente')], default='agent', max_length=10, verbose_name='Kullanıcı Rolü')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Adı / Ünvanı')),
                ('tckn_vkn', models.CharField(max_length=14, unique=True, verbose_name='TCKN / VKN')),
                ('customer_type', models.CharField(choices=[('individual', 'Bireysel'), ('corporate', 'Kurumsal')], default='individual', max_length=10, verbose_name='Müşteri Tipi')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-posta')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu Acente')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('policy_id', models.AutoField(primary_key=True, serialize=False)),
                ('policy_number', models.CharField(max_length=50, unique=True, verbose_name='Poliçe Numarası')),
                ('policy_type', models.CharField(max_length=50, verbose_name='Sigorta Tipi (Kasko, Trafik vb.)')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(verbose_name='Bitiş Tarihi')),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prim Tutarı')),
                ('document_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Döküman URL/Yolu')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('expired', 'Süresi Doldu'), ('cancelled', 'İptal Edildi')], default='active', max_length=10, verbose_name='Poliçe Durumu')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='policy_management.customer', verbose_name='Müşteri')),
                ('issued_by_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_policies', to=settings.AUTH_USER_MODEL, verbose_name='Düzenleyen Acente')),
            ],
            options={
                'verbose_name': 'Poliçe',
                'verbose_name_plural': 'Poliçeler',
            },
        ),
    ]
