# Generated by Django 5.2.7 on 2025-10-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='policies/documents/', verbose_name='Poliçe Dökümanı (PDF)'),
        ),
    ]
