# Generated by Django 5.2.7 on 2025-11-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy_management', '0002_policy_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='document_url',
        ),
    ]
