# Generated by Django 5.2.7 on 2025-11-01 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_management', '0003_remove_policy_document_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Sigorta Şirketi')),
                ('policy_type', models.CharField(choices=[('Kasko', 'Kasko'), ('Trafik', 'Trafik Sigortası'), ('DASK', 'DASK/Konut')], max_length=50, verbose_name='Sigorta Tipi')),
                ('premium_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prim Tutarı')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Teklifi Alan Acente')),
            ],
            options={
                'verbose_name': 'Fiyat Teklifi',
                'verbose_name_plural': 'Fiyat Teklifleri',
            },
        ),
    ]
