# Generated by Django 5.2.7 on 2025-11-03 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_management', '0004_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policy_management.customer', verbose_name='Müşteri'),
        ),
    ]
