# Generated by Django 5.2.7 on 2025-11-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_management', '0005_quote_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
    ]
