# Generated by Django 5.2.7 on 2025-11-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_management', '0006_customer_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İl'),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İlçe'),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sokak/Cadde'),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_zipcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Posta Kodu'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tckn',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='TCKN'),
        ),
    ]
