# Generated by Django 5.2.7 on 2025-11-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_management', '0007_customer_address_city_customer_address_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tckn',
            field=models.CharField(default=0, max_length=11, unique=True, verbose_name='TCKN'),
            preserve_default=False,
        ),
    ]
