# Generated by Django 5.2.7 on 2025-11-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_management', '0008_alter_customer_tckn'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tckn',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='TCKN'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi'),
        ),
    ]
