# Generated by Django 5.2.7 on 2025-11-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_management', '0009_quote_updated_at_alter_customer_tckn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'Bireysel'), ('corporate', 'Kurumsal')], default='individual', max_length=10, verbose_name='TCKN/VKN (Eski Alan)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tckn_vkn',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='TCKN/VKN (Eski Alan)'),
        ),
    ]
