# Generated by Django 5.2.7 on 2025-11-05 19:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_management', '0010_alter_customer_customer_type_alter_customer_tckn_vkn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Oluşturma Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'Bireysel'), ('corporate', 'Kurumsal')], default='individual', max_length=10, verbose_name='Müşteri Tipi'),
        ),
    ]
