"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w-hv8kmxjsohe(rkp0v3(xb5hz53)^m4qmelek(wjpqg)d9tk6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    'www.pythonanywhere.com',  # PA sunucusu için gerekli
    'poyrazzz.pythonanywhere.com', # Kendi alan adınız
    # Eğer alan adınız varsa, onu da buraya ekleyin: 'sigortasistemi.com'

    # 🚨 YENİ EKLEME (Lokalde çalışmak için kritik):
    '127.0.0.1', 
    'localhost',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'policy_management',
    'import_export',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'tr'

TIME_ZONE = 'Europe/Istanbul'

USE_L10N = True
USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # <-- YENİ EKLEME

STATICFILES_DIRS = [
    # Projenin root seviyesinde ekleyebileceğiniz statik dosyaları işaret eder
    # os.path.join(BASE_DIR, 'static'), 
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# core/settings.py (En alta ekleyin)

AUTH_USER_MODEL = 'policy_management.CustomUser'



# Yeni giriş URL'mizi LOGIN_URL olarak tanımlıyoruz
LOGIN_URL = 'login' 

# Giriş başarılı olduktan sonra Acente Dashboard'a yönlendir (Aynı kalacak)
LOGIN_REDIRECT_URL = '/agent/' 

# Çıkıştan sonra yeni giriş sayfasına yönlendir (Adını değiştirdik)
LOGOUT_REDIRECT_URL = 'login'

# ----------------------------------------------------------------------
# 📂 MEDYA (DOSYA YÜKLEME) AYARLARI
# ----------------------------------------------------------------------

# 1. MEDIA_ROOT: Yüklenen dosyaların sunucuda fiziksel olarak nereye kaydedileceğini tanımlar.
# Bu, BASE_DIR içinde 'media' adında bir klasör olmalıdır.
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 2. MEDIA_URL: Tarayıcı üzerinden bu dosyalara erişim URL'si.
MEDIA_URL = '/media/'

# ----------------------------------------------------------------------
# 🔒 SİGORTA ŞİRKETİ API ANAHTARLARI
# BU BİLGİLERİ ASLA PAYLAŞMAYIN VEYA GITHUB'A YÜKLEMEYİN!
# ----------------------------------------------------------------------
# (Gerçek anahtarları aldığınızda burayı doldurun)

ALLIANZ_API_KEY = "SIZIN_ALLIANZ_ANAHTARINIZ"
ALLIANZ_API_SECRET = "SIZIN_ALLIANZ_SIFRENIZ"

DOGA_API_USER = "SIZIN_DOGA_KULLANICI_ADINIZ"
DOGA_API_PASS = "SIZIN_DOGA_SIFRENIZ"

TURKIYE_API_TOKEN = "SIZIN_TURKIYE_TOKENINIZ"